# Use default data source
- nr_companies_per_country:
    sql: >
        select country, count(1) as cnt from Companies group by country
    data-field: cnt

# Sub queries
# This will register two metrics:
# - response_time_count with cnt as value
# - response_time_sum with rt as value
- response_time:
    sql: >
        select count(*) as cnt, sum(response_time) as rt from requests
    sub-metrics:
      count: cnt
      sum: rt
    interval: 30s